[package]
name = "rust-sftp"
version = "0.1.0"
authors = ["Thomas Newman <tnewman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.6.0"
