[package]
name = "dray"
version = "0.1.0"
authors = ["Thomas Newman <tnewman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
async-trait = "0.1.42"
bytes = "1.0.1"
env_logger = "0.8.3"
futures = "0.3.13"
log = "0.4.14"
thrussh = "0.32.7"
thrussh-keys = "0.20.2"
tokio = { version = "1.2.0", features = ["full"] }

# S3 Dependencies
rusoto_core = "0.46.0"
rusoto_s3 = "0.46.0"
