[package]
name = "dray"
version = "0.1.0"
authors = ["Thomas Newman <tnewman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = "1.5"
chrono = "0.4"
dotenv = "0.15"
env_logger = "0.10"
envy = "0.4"
futures = "0.3"
hex = "0.4.3"
log = "0.4"
serde = "1.0"
thiserror = "1.0"
russh = { version = "0.40.0", features = ["flate2", "openssl"] }
russh-keys = { version = "0.40.0", features = ["openssl"] }
tokio = { version = "1.34", features = ["full"] }
uuid = { version = "1.6.1", features = ["v4"], default-features = false }

# S3 Dependencies
aws-config = "1.1.1"
aws-sdk-s3 = "1.11.0"

[dev-dependencies]
rand = "0.8"
tempfile = "3.8"
