[package]
name = "dray"
version = "0.1.0"
authors = ["Thomas Newman <tnewman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
chrono = "0.4"
dotenv = "0.15"
env_logger = "0.9"
envy = "0.4"
futures = "0.3"
hex = "0.4.3"
log = "0.4"
serde = "1.0"
thiserror = "1.0"
thrussh = { version = "0.33", features = ["flate2", "openssl"] }
thrussh-keys = { version = "0.21", features = ["openssl"] }
tokio = { version = "1.9", features = ["full"] }
uuid = { version = "0.8", features = ["v4"], default-features = false }

# S3 Dependencies
rusoto_core = "0.47"
rusoto_s3 = "0.47"

[dev-dependencies]
async_once = "0.2"
http = "0.2"
lazy_static = "1.4"
