version: "3"
services:
  minio:
    image: index.docker.io/minio/minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_REGION_NAME: "custom"
      MINIO_ROOT_USER: "miniouser"
      MINIO_ROOT_PASSWORD: "miniopass"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-data:
